name: vortex
description: Vortex — Cross-platform messenger
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  socket_io_client: ^2.0.3+1
  http: ^1.1.0
  image_picker: ^1.0.4
  file_picker: ^8.1.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  intl: 0.20.2
  uuid: ^4.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
